name: Build
on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string

jobs:
  build:
    runs-on: big-runner-1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: ls -lah /tmp
      - run: sudo ls -lh /var/lib/docker

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build containers
        run: docker compose build --progress=plain
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          ORG: jitolabs
          TAG: ${{ inputs.TAG }}

      - run: ls -lah /tmp
