name: Clean Code Check
on:
  workflow_call:
    secrets:
      GHUB_TOKEN:
        required: true

jobs:
  clippy_and_udeps_check:
    runs-on: big-runner-1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'


      - run: echo ${{github}};
        shell: bash
      - run: echo ${{env}};
        shell: bash
      - run: echo ${{vars}};
        shell: bash

      - run: echo ${{job}};
        shell: bash

      - run: echo ${{steps}};
        shell: bash

      - run: echo ${{runner}};
        shell: bash
      - run: echo ${{secrets}};
        shell: bash
      - run: echo ${{strategy}};
        shell: bash
      - run: echo ${{matrix}};
        shell: bash
      - run: echo ${{needs}};
        shell: bash
      - run: echo ${{inputs}};
        shell: bash
      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          args: --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked

      - name: Run cargo udeps
        uses: actions-rs/cargo@v1
        with:
          command: udeps
