name: Clean Code Check
on:
  workflow_call:
    secrets:
      GHUB_TOKEN:
        required: true

jobs:
  clippy_and_udeps_check:
    runs-on: big-runner-1
    steps:
      - name: Setup Rust
        uses: ./.github/workflows/setup_rust_native.yaml

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-features

      - name: Install udeps
        run: "cargo install cargo-udeps"

      - name: Run cargo udeps
        uses: actions-rs/cargo@v1
        with:
          command: udeps
