name: Clean Code Check
on:
  workflow_call:
    secrets:
      GHUB_TOKEN:
        required: true

jobs:
  clippy_and_udeps_check:
    runs-on: big-runner-1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'


      - run: echo ${{toJson(github)}};
        shell: bash
      - run: echo ${{toJson(env)}};
        shell: bash
      - run: echo ${{toJson(vars)}};
        shell: bash

      - run: echo ${{toJson(job)}};
        shell: bash

      - run: echo ${{toJson(steps)}};
        shell: bash

      - run: echo ${{toJson(runner)}};
        shell: bash
      - run: echo ${{toJson(secrets)}};
        shell: bash
      - run: echo ${{toJson(strategy)}};
        shell: bash
      - run: echo ${{toJson(matrix)}};
        shell: bash
      - run: echo ${{toJson(needs)}};
        shell: bash
      - run: echo ${{toJson(inputs)}};
        shell: bash
      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{toJson( secrets.GHUB_TOKEN )}}
          args: --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked

      - name: Run cargo udeps
        uses: actions-rs/cargo@v1
        with:
          command: udeps
