name: Test
on:
  workflow_call:

jobs:
  test:
    runs-on: big-runner-1
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Rust
      uses: ./.github/workflows/setup_rust_native.yaml

    - name: Run tests
      run: RUST_LOG=info cargo test
